DROP TABLE NAIC IF EXISTS;

CREATE TABLE NAIC(
NAIC_ID VARCHAR(9) NOT NULL,
COMPANY_NAME VARCHAR(40) NOT NULL,
GROUP_ID VARCHAR(9),
STATEMENT_TYPE VARCHAR(9),
COMPANY_STATUS VARCHAR(5),
STATE_ABBR VARCHAR(2));
COMMENT ON TABLE NAIC IS 'NAICS';
COMMENT ON COLUMN NAIC.NAIC_ID IS 'UNIQUE NAIC ID';
COMMENT ON COLUMN NAIC.COMPANY_NAME IS 'COMPANY NAME';
COMMENT ON COLUMN NAIC.GROUP_ID IS 'GROUP ID';
COMMENT ON COLUMN NAIC.STATEMENT_TYPE IS 'STATEMENT TYPE';
COMMENT ON COLUMN NAIC.COMPANY_STATUS IS 'COMPANY STATUS';
COMMENT ON COLUMN NAIC.STATE_ABBR IS 'STATE ABBREVIATION FOR STATE LOCATION OF NAIC';

ALTER TABLE NAIC ADD CONSTRAINT PK_NAIC PRIMARY KEY (NAIC_ID);

DROP TABLE BANK IF EXISTS;

CREATE TABLE BANK(
ROUTINGNUMBER VARCHAR(9) NOT NULL,
BANK_NAME VARCHAR(40) NOT NULL,
CITY_NAME VARCHAR(40) NOT NULL,
STATE_ABBR VARCHAR(2) NOT NULL);
COMMENT ON TABLE BANK IS 'BANKS';
COMMENT ON COLUMN BANK.ROUTINGNUMBER IS 'UNIQUE ROUTING NUMBER';
COMMENT ON COLUMN BANK.BANK_NAME IS 'NAME OF THE BANK';
COMMENT ON COLUMN BANK.CITY_NAME IS 'CITY LOCATION OF BANK';
COMMENT ON COLUMN BANK.STATE_ABBR IS 'STATE ABBREVIATION FOR STATE LOCATION OF BANK';

ALTER TABLE BANK ADD CONSTRAINT PK_BANK PRIMARY KEY (ROUTINGNUMBER);
